###########################
# Window
###########################
window:
  startup_mode: 'Maximized'

###########################
# Colors
###########################
colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'

  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'

  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'

  selection:
    text: CellForeground
    background: '#4c566a'

  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'

    bar:
      background: '#434c5e'
      foreground: '#d8dee9'

  normal:
    black: '#2E3436'
    red: '#CC0000'
    green: '#4E9A06'
    yellow: '#C4A000'
    blue: '#3465A4'
    magenta: '#75507B'
    cyan: '#06989A'
    white: '#D3D7CF'
  bright:
    black: '#555753'
    red: '#EF2929'
    green: '#8AE234'
    yellow: '#FCE94F'
    blue: '#729FCF'
    magenta: '#AD7FA8'
    cyan: '#34E2E2'
    white: '#EEEEEC'

###########################
# Font
###########################
font:
  size: 11.5

  normal:
    family: 'SauceCodePro Nerd Font Mono'
    style: Bold

###########################
# Mouse
###########################
mouse_bindings:
  - { mouse: Left,  mods: Shift, action: Copy }
  - { mouse: Right, mods: Shift, action: Paste }
